imports:
    - php
build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
    environment:
        php:
            version: 7.2.0
    tests:
            -
               command: ./vendor/bin/phpunit --coverage-clover=coverage
               coverage:
                   file: coverage
                   format: php-clover
tools:
    php_changetracking: true
    php_sim: true
    php_pdepend: true
    php_mess_detector: true
    php_analyzer: true
    php_cs_fixer: true
    sensiolabs_security_checker: true